### ISSUE TITLE
use pipenv for python dependency management

### ISSUE THREAD

**Issue by ilya-epifanov** [xobs/lxbuildenv#2]
Here's a starting point `Pipfile`:

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
pylint = "*"

[packages]
litex = { path = "deps/litex", editable = true }
litex_boards = { path = "deps/litex_boards", editable = true }
litescope = { path = "deps/litescope", editable = true }
migen = { path = "deps/migen", editable = true }
pythondata-software-compiler_rt = { path = "deps/pythondata-software-compiler_rt", editable = true }
pythondata-cpu-vexriscv = { path = "deps/pythondata-cpu-vexriscv", editable = true }
m2r = "*"
recommonmark = "*"
sphinx-rtd-theme = "*"
sphinx-autodoc-typehints = "*"
sphinxcontrib-wavedrom = "*"
```

It integrates well with IDEs (Python Language Server has to be switched to 'weekly' insiders channel in VSCode at the moment, PyCharm works well as-is).

The "downside" is that you have to run `pipenv install` every time you add/remove dependencies. Which is not a big deal, IMO. Also, the `LX_DEPENDENCY` magic can be removed then.

This will allow `lxbuildenv` to focus on actually initializing a project with a proper structure, managing the `deps` directory and keeping links to it in the `Pipfile`.
